services:
  - type: web
    name: eyearbook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn eyearbook.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eyearbook.settings
