# Generated by Django 5.2 on 2025-06-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=150)),
                ('ambition', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='graduate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.graduate'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
