# Generated by Django 5.2 on 2025-06-12 00:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_graduatetracerform_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
