# Generated by Django 5.2 on 2025-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_graduate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='graduates/'),
        ),
    ]
